print("Hola mundo")
print("ahora vamos a meterle pero desde el github")
print("Pega todo como funciona esto ahora mandamos de vuelta al github desde el visual")
print("Este es un print que vamos a hacer cachiai antes de hacer un undo mortal")
print("Jeje")